### ISSUE TITLE
problem when creating a new container

### ISSUE THREAD

**Issue by Mecha-Labs** [Moe-hacker/termux-container#14]
![Screenshot_20220103-070902_Termux](https://user-images.githubusercontent.com/91070944/147893058-7b12fb49-3c3e-4fe1-9a1d-20a5c34077dd.png)
Is there any way to fix this? this happened after changes to this repository 10 hours ago,  Hopefully there is a way to solve this problem

**Comment by Moe-hacker** [comment]
It looks like /data/data/com.termux/files/ubuntu already exists,you should delete it or use another directory.
 Existing directories cannot be used to store containers. This is because it is not safe, and if there is another container in the directory , it may cause the container broken.
![Screenshot_20220103-150700_Termux](https://user-images.githubusercontent.com/76621454/147907804-19a49a64-1dcb-41f6-bb83-77e9fc274365.png)
